name: Build

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set build number
      run: echo BUILDNUM=$GITHUB_REF_NAME.$(TZ=America/Los_Angeles date +%Y%m%d).$GITHUB_RUN_NUMBER >> $GITHUB_ENV
    - name: Show build number
      run: echo "Build Number is ${{ env.BUILDNUM }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
